version: "3.9"

services:
  go-app:
    container_name: go-app
    image: github.com/alexander-pastana/go-api-lab-lab
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    env_file:
      - .env

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata: {}